spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/github.ae/github.ae.yaml
namespace: ApiClients\Client\GitHubAE
destination:
  root: ../
  source: src
  test: tests
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
