spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/github.ae/github.ae.yaml
namespace:
  source: ApiClients\Client\GitHubAE
  test: ApiClients\Tests\Client\GitHubAE
destination:
  root: ../
  source: src
  test: tests
templates:
  dir: ../templates
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
