<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHubAE\Schema;

use ApiClients\Client\GitHubAE\Error as ErrorSchemas;
use ApiClients\Client\GitHubAE\Hydrator;
use ApiClients\Client\GitHubAE\Operation;
use ApiClients\Client\GitHubAE\Schema;
use ApiClients\Client\GitHubAE\WebHook;
final readonly class EnterpriseOverview
{
    public const SCHEMA_JSON = '{"type":"object","properties":{"repos":{"title":"Repository Enterprise Stats","required":["total_repos","root_repos","fork_repos","org_repos","total_pushes","total_wikis"],"type":"object","properties":{"total_repos":{"type":"integer"},"root_repos":{"type":"integer"},"fork_repos":{"type":"integer"},"org_repos":{"type":"integer"},"total_pushes":{"type":"integer"},"total_wikis":{"type":"integer"}}},"hooks":{"title":"Hooks Enterprise Stats","required":["total_hooks","active_hooks","inactive_hooks"],"type":"object","properties":{"total_hooks":{"type":"integer"},"active_hooks":{"type":"integer"},"inactive_hooks":{"type":"integer"}}},"pages":{"title":"Enterprise Pages Stats","required":["total_pages"],"type":"object","properties":{"total_pages":{"type":"integer"}}},"orgs":{"title":"Enterprise Organization Stats","required":["total_orgs","disabled_orgs","total_teams","total_team_members"],"type":"object","properties":{"total_orgs":{"type":"integer"},"disabled_orgs":{"type":"integer"},"total_teams":{"type":"integer"},"total_team_members":{"type":"integer"}}},"users":{"title":"Enterprise User Stats","required":["total_users","admin_users","suspended_users"],"type":"object","properties":{"total_users":{"type":"integer"},"admin_users":{"type":"integer"},"suspended_users":{"type":"integer"}}},"pulls":{"title":"Enterprise Pull Request Stats","required":["total_pulls","merged_pulls","mergeable_pulls","unmergeable_pulls"],"type":"object","properties":{"total_pulls":{"type":"integer"},"merged_pulls":{"type":"integer"},"mergeable_pulls":{"type":"integer"},"unmergeable_pulls":{"type":"integer"}}},"issues":{"title":"Enterprise Issue Stats","required":["total_issues","open_issues","closed_issues"],"type":"object","properties":{"total_issues":{"type":"integer"},"open_issues":{"type":"integer"},"closed_issues":{"type":"integer"}}},"milestones":{"title":"Enterprise Milestone Stats","required":["total_milestones","open_milestones","closed_milestones"],"type":"object","properties":{"total_milestones":{"type":"integer"},"open_milestones":{"type":"integer"},"closed_milestones":{"type":"integer"}}},"gists":{"title":"Enterprise Gist Stats","required":["total_gists","private_gists","public_gists"],"type":"object","properties":{"total_gists":{"type":"integer"},"private_gists":{"type":"integer"},"public_gists":{"type":"integer"}}},"comments":{"title":"Enterprise Comment Stats","required":["total_commit_comments","total_gist_comments","total_issue_comments","total_pull_request_comments"],"type":"object","properties":{"total_commit_comments":{"type":"integer"},"total_gist_comments":{"type":"integer"},"total_issue_comments":{"type":"integer"},"total_pull_request_comments":{"type":"integer"}}}}}';
    public const SCHEMA_TITLE = '';
    public const SCHEMA_DESCRIPTION = '';
    public const SCHEMA_EXAMPLE_DATA = '{"repos":{"totalRepos":13,"rootRepos":13,"forkRepos":13,"orgRepos":13,"totalPushes":13,"totalWikis":13},"hooks":{"totalHooks":13,"activeHooks":13,"inactiveHooks":13},"pages":{"totalPages":13},"orgs":{"totalOrgs":13,"disabledOrgs":13,"totalTeams":13,"totalTeamMembers":13},"users":{"totalUsers":13,"adminUsers":13,"suspendedUsers":13},"pulls":{"totalPulls":13,"mergedPulls":13,"mergeablePulls":13,"unmergeablePulls":13},"issues":{"totalIssues":13,"openIssues":13,"closedIssues":13},"milestones":{"totalMilestones":13,"openMilestones":13,"closedMilestones":13},"gists":{"totalGists":13,"privateGists":13,"publicGists":13},"comments":{"totalCommitComments":13,"totalGistComments":13,"totalIssueComments":13,"totalPullRequestComments":13}}';
    public function __construct(public ?Schema\EnterpriseRepositoryOverview $repos, public ?Schema\EnterpriseHookOverview $hooks, public ?Schema\EnterprisePageOverview $pages, public ?Schema\EnterpriseOrganizationOverview $orgs, public ?Schema\EnterpriseUserOverview $users, public ?Schema\EnterprisePullRequestOverview $pulls, public ?Schema\EnterpriseIssueOverview $issues, public ?Schema\EnterpriseMilestoneOverview $milestones, public ?Schema\EnterpriseGistOverview $gists, public ?Schema\EnterpriseCommentOverview $comments)
    {
    }
}
